common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  min_messages: warning

development:
  <<: *common
  username: dev
  password: 1
  database: stavtooth_development

production:
  pool: 20
  database: stavtooth
